# Config file used by .github/workflows/labeler.yml

# This file matches file/folder changes to labels. See https://github.com/actions/labeler for more information.

# e.g to add the test label to any changes in the /tests directory:

# test:
#   - tests/*

ghActions:
  - .github/*
documentation:
  - '**/*.md'
jenkins:
  - build-farm/*
aix:
  - build-farm/platform-specific-configurations/aix.sh
alpine-linux:
  - build-farm/platform-specific-configurations/alpine-linux.sh
macos:
  - build-farm/platform-specific-configurations/mac.sh
solaris:
  - build-farm/platform-specific-configurations/solaris.sh
windows:
  - build-farm/platform-specific-configurations/windows.sh
docker:
  - docker/*
  - docker-build.sh
testing:
  - tests/*
security:
  - security/*
  - SECURITY.md
  - sbin/sig_check/*
installer:
  - build-farm/sign-releases.sh
  - sign.sh
