# ********************************************************************************
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

# Label and project adding bot, see .github/labeler.yml for config

name: "Labeller & Project Manager"
on:
  pull_request_target:
  issues:
  issue_comment:

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    name: Assign Labels
    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      if: ${{ github.event.pull_request }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4.0.0
      with:
        github-token: "${{secrets.GITHUB_TOKEN}}"
        config-path: .github/regex_labeler.yml
